### ISSUE TITLE
switch to fetch api for ajax

### ISSUE THREAD

**Issue by sgratzl** [phovea/phovea_core#10]
see https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

examples how to use: https://github.com/github/fetch

**Comment by ngehlenborg** [comment]
I see that it lacks support in WebKit, which we should be supporting.

**Comment by sgratzl** [comment]
see also https://github.com/phovea/generator-phovea/issues/22

**Comment by thinkh** [comment]
Done with PR #15 and #23.
