### ISSUE TITLE
Missing values in numerical vectors are treated as empty strings/0, should be NAN

### ISSUE THREAD

**Issue by alexsb** [phovea/phovea_core#102]
These lines: 

https://github.com/Caleydo/phovea_demos/commit/4e3d3f8f54d24cdfca31ddaf24b08eb757af53a7#diff-6d0c82cc6c66c68f45e4f2263d535897R237

Produce this output: 

![image](https://cloud.githubusercontent.com/assets/2039375/23866312/0dc71132-07de-11e7-8dd1-35b1c0f4c2d1.png)

This clearly demonstrates that missing values in numerical columns aren't treated as NAN but either as 0 or empty strings. 

NAN would be the correct approach. 

Not 100% certain whether that's a client or server bug, but now seems more like client.

**Comment by sgratzl** [comment]
I don't know how to use the phovea_demos cause it seems like it doesn't come with data anymore?

**Comment by alexsb** [comment]
I built a workspace around it and run docker.

**Comment by alexsb** [comment]
Great, thanks!
