### ISSUE TITLE
The length of the output of vector.data() is sometimes different than that of vector.ids() and vector.names()

### ISSUE THREAD

**Issue by cnobre** [phovea/phovea_core#106]
We create a view on a phovea table by  doing a union of several different ranges (as selected by the user). 

Some combinations of ranges (particularly those in very large sets) trigger an error since the output of vector.data() is one element shorter than the output of vector.names() and vector.ids().

You can reproduce this error by starting up Lineage and selecting the first and 3rd families in the top left (using the command key to select multiple families). 

The console.log shows the length of vector.data, vector.names() and vector.ids() and you can see that the .data() is off by one.

**Comment by alexsb** [comment]
Note that it's possible that some rows in this table have the same name/ID.

**Comment by sgratzl** [comment]
> using the command key to select multiple families

windows systems don't have a command key ;)

**Comment by cnobre** [comment]
aha, never mind. It was a problem in a pre-processing step. Thanks anyway Sam!
