### ISSUE TITLE
Typescript 3.0

### ISSUE THREAD

**Issue by ghost** [phovea/phovea_core#142]
Because of the new Typescript version, we have to check nulls and set explizit types.
There are a lot of problems with the vector classes.

Could you have a look over that (because I have no idea why there is a difference between AVector, ANamedVector, VectorView,...) and why idType(s) have different type declarations.

see [branch release-3.0](https://github.com/phovea/phovea_core/tree/release-3.0)

**Comment by sgratzl** [comment]
all compile errors should be fixed. At least `npm run compile` runs through

**Comment by ghost** [comment]
could you please run npm run test because I don't know the test and also not the code
