### ISSUE TITLE
phovea_core: Release 3.0.0

### ISSUE THREAD

**Issue by ghost** [phovea/phovea_core#143]
@sgratzl ich hab jetzt nur noch den test, dass bei Range1D › all › length 0 anstelle von NaN kommt.
ich finde auch keinen code, der das berücksichtigt;
soll ich da wirklich den code dementsprechend ändern (sprich ein if in der size-methode) oder den test dementsprechend ändern

**Comment by ghost** [comment]
because of the cicle implementation in the member classes we get the following error (that can't be fixed):
ERROR: /workspaces/releases/phovea_core/src/2D.ts[983, 29]: variable 'Path' used before declaration
ERROR: /workspaces/releases/phovea_core/src/2D.ts[985, 36]: variable 'Path' used before declaration
ERROR: /workspaces/releases/phovea_core/src/iterator.ts[65, 16]: variable 'TransformIterator' used before declaration
ERROR: /workspaces/releases/phovea_core/src/matrix/AMatrix.ts[84, 16]: variable 'MatrixView' used before declaration
ERROR: /workspaces/releases/phovea_core/src/table/ATable.ts[38, 16]: variable 'TableView' used before declaration
ERROR: /workspaces/releases/phovea_core/src/vector/AVector.ts[66, 16]: variable 'VectorView' used before declaration

**Comment by ghost** [comment]
solution would be:
* change the class hierarchy or
* set no-use-before-declare to false

**Comment by thinkh** [comment]
See PR #148.

**Comment by thinkh** [comment]
The TypeScript 3 release will have a higher version number than 3.0.0. I close this ticket as the PR is already filed.
