### ISSUE TITLE
multi tab/window support

### ISSUE THREAD

**Issue by sgratzl** [phovea/phovea_core#21]
https://github.com/Caleydo/caleydo_web_container/issues/61

with multiple monitors this feature would be very useful. 

problems: communication, 
- need a master page with popup who are the slave  
- not that easy communicating between tabs: -> serialization needed, so no way to share references? 
  - via shared sessionStorage?, 
  - server in the middle: websockets?

thoughts:
- slave: own site -> with a custom application which intercepts and communicates? 
- if the structure of the code is well organized, we could exchange specific javascript files with a "slave" version
- real multi-tabs support vs window + popups

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_core/tree/feature_21_multi_tab_support

**Comment by thinkh** [comment]
Result:

![multi-tab-support](https://cloud.githubusercontent.com/assets/5851088/23745006/ea1c13c4-04b6-11e7-8894-4c4d7c821cd2.gif)
