### ISSUE TITLE
geom constructors vs. factory methods?

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_core#26]
In geom, we have both constructors and factory methods, for example:
```
export function circle(x:number, y:number, radius:number):Circle {
  return new Circle(x, y, radius);
}
```
What do we need both for?

**Comment by thinkh** [comment]
Maybe some legacy code from the old Caleydo Web package.json code?
@sgratzl might know more.

**Comment by sgratzl** [comment]
I like the factory pattern. Especially in JavaScript where you can't be sure whether you return just an object or a new instance of an object or a function that acts like an object
