### ISSUE TITLE
How to build caleydo_core?

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_core#3]
I see the same errors [on travis](https://travis-ci.org/Caleydo/caleydo_core/builds/161934107) as I see locally when I try `tsc range.ts` Is there some other command I should use to build a single file or all of caleydo_core?

**Comment by sgratzl** [comment]
see also Caleydo/caleydo_web_container#157

**Comment by mccalluc** [comment]
I'm on the way to a self-contained build of caleydo_core in #4, just not sure if it's the right way.

**Comment by sgratzl** [comment]
the thing is in the current version (just because of the typings reference in the code), the files won't compile in the regular setting anymore. And the core doesn't have any external dependencies.

**Comment by sgratzl** [comment]
`npm run build`
