### ISSUE TITLE
In the core/vis/d3, do we have more modularity than we need?

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_core#48]
Are the divisions between core/vis/d3 necessary and useful? Right now, they're making my life harder, and I'm not sure about the motivation. Immediate issue:
- I'm working on https://github.com/phovea/phovea_vis/pull/18
- Although it manifests as a vis problem, my best guess right now is that the behavior of MatrixView in core is buggy. That class is not exported (discuss testing private members at #47), so without pushing a new version of core, there's no way for me to test that method from vis.
- But if I write the test in core, turning on export temporarily, I can't use `parseMatrix` because that's in d3, and and d3 is not dependency of core.
- And maybe I could do that, but circular dependencies seem like a recipe for trouble.

I can approach this from another direction, but is there anything that splitting core/vis/d3 into separate repos makes easier?

**Comment by sgratzl** [comment]
related question: why is d3 moving from a monolitic approach (v3) to a split one (v4)?

I would rewrite the parser module to avoid d3 and move it to the core. However, I don't want external dependencies like d3 in the core.

**Comment by mccalluc** [comment]
Sorry, I should have made it clear that I was referring to phovea_d3, not d3.

**Comment by sgratzl** [comment]
I know but if we merge phovea_d3 in phovea_core, phovea_core will have a d3 dependency

**Comment by mccalluc** [comment]
I may have jumped to a diagnosis too soon: Maybe there's a better way to approach the particular problem I have?

(Not sure that it sheds much light, but here's a visualization of the D3v4 dependency structure: http://bl.ocks.org/alisd23/5762cc5912253c4febeb) (Only works in Chrome for me.)

**Comment by sgratzl** [comment]
related #56 -> allows to test the core with test data
