### ISSUE TITLE
Get typedoc working again

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_core#54]
Typedoc should be working for 2.0: https://github.com/TypeStrong/typedoc/issues/234 -> https://github.com/TypeStrong/typedoc/pull/290

- [ ] Turn on doc generation in travis for core, d3, and vis, at least.
- [ ] deploy docs to s3
- [ ] link to docs from phovea.github.io

**Comment by sgratzl** [comment]
but the issue is: https://github.com/TypeStrong/typedoc/issues/315

**Comment by mccalluc** [comment]
Good to know: I didn't know what the details were. It doesn't look like a fix for that is coming any time soon. Options:
- Give up on generated documentation for the immediate future?
- Try to make a PR for that issue ourselves?
- Try one of the hacks given in the comments?
- Change our code so it doesn't need lib?

I'll put this on the agenda again: I didn't realize what the issue was.

**Comment by sgratzl** [comment]
> Try one of the hacks given in the comments?

we can locally try e.g. for lineup.js

**Comment by mccalluc** [comment]
So when I make the edit in place, it works: I have seen the generated docs.

But, how do we apply that patch: The obvious answer is to fork that repo, make the edits in the fork, and then reference the fork from our package.json. Except I get this error:
```
phovea_core$ npm run docs

> phovea_core@0.0.3 docs /Users/chuck/github/phovea/phovea_core
> typedoc --options typedoc.json src/**.ts

module.js:472
    throw err;
    ^

Error: Cannot find module '../lib/cli.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chuck/github/phovea/phovea_core/node_modules/typedoc/bin/typedoc:12:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Might be more clear tomorrow...

**Comment by sgratzl** [comment]
my hacked version:
https://github.com/Caleydo/lineupjs/blob/pre_release/package.json#L42
replace the typedoc file on demand with the patched one

**Comment by mccalluc** [comment]
That's a better idea: Thanks!
```
"scripts": {
...
"docs": "cp -r typedoc_hacked ./node_modules/typedoc/bin/typedoc && typedoc --options typedoc.json src",
...
```

I'll get this into the other repos, and the generator.

**Comment by sgratzl** [comment]
please first test and fix the core and then we can think about batch rolling it out.

**Comment by sgratzl** [comment]
https://github.com/TypeStrong/typedoc/releases/tag/v0.5.3 is out and solves the problem

**Comment by sgratzl** [comment]
typedocs will be build as part of the build process. However, they are not persisted so far
