### ISSUE TITLE
CompositeRange1D toBase() -> error with empty groups

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_core#70]
* Release number or git hash: 1256f2d93a36306886957f53949c61cbc69b7bf1
* Web browser version and OS: Chrome 55, Windows 10
* Environment (local or deployed): local

### Steps to reproduce

1. Check-out, install and run [stratomex.js](Caleydo/stratomex.js)
2. Add sample datasets that contain stratifications
3. Open stratomex in browser with new provenance graph 
4. Add a stratification and see console log

### Observed behavior

* Web browser console errors (including tracebacks)
```
app.js:36979 Uncaught (in promise) TypeError: Cannot read property 'iter' of undefined
    at toBase (app.js:36979)
    at new CompositeRange1D (app.js:36992)
    at composite (app.js:10058)
    at categorical2partitioning (app.js:11524)
    at app.js:38527
toBase @ app.js:36979
CompositeRange1D @ app.js:36992
composite @ app.js:10058
categorical2partitioning @ app.js:11524
(anonymous) @ app.js:38527
```
Refers to CompositeRange1D toBase() in line 8ff.

* Static or animated images showing the UI behavior

![compositerange1d_tobase](https://cloud.githubusercontent.com/assets/5851088/21688852/a18976c0-d36e-11e6-9196-9b8bb2583845.PNG)

### Expected behavior
* Load `groups` correctly or check for empty `groups`

**Comment by thinkh** [comment]
Further investigation point to [categorical2partitioning](https://github.com/phovea/phovea_core/blob/master/src/datatype.ts#L152), where the data differs from the categories and no indecies are pushed to group.

![dataype_categorical2partitioning](https://cloud.githubusercontent.com/assets/5851088/21690319/ffcc5130-d373-11e6-9080-6cac8b282778.PNG)

**Comment by thinkh** [comment]
The data contains the indicies to the categorical strings, but not the categories as strings. One solution would be that the server sends the correct (mapped) data. 

The other solution is that each category comes as object with value and label. 

@sgratzl Please decide for a solution. I don't know the side-effects for both solutions on other projects.

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_data_hdf/pull/8

**Comment by sgratzl** [comment]
since the related pull request is merged -> retest

**Comment by thinkh** [comment]
I can't reproduce this after the update. Therefore I close this issue.
