### ISSUE TITLE
phovea table .objects() method does not return correct columns after .view() call

### ISSUE THREAD

**Issue by anniecherk** [phovea/phovea_core#91]
### Steps to reproduce

1. Reproduce by pulling this code & watching the console.log()'s : https://github.com/Caleydo/lineage/blob/da92c6232a825f552c444949bab99be332094d78/src/attributeData.ts#L77

Relevant code begins around line 77

### Observed behavior
The problem is that I'm initializing the table to a view which has only non "idtype" columns (so some columns get excluded). I've got console logs to verify that the expected columns are being added, and then I request the view corresponding to those columns from the server. I verify that
```
activeView.cols()
```
returns the expected column names, and it does.
I then check what is contained in
```
activeView.objects()
```
which is the "row data" meaning it is a list of objects, one for each row, each of which is a dictionary of column names to values. The columns in these objects are totally different though. I'm accessing the same object.  Any ideas for what might be wrong?

I just pushed code that logs exactly what I'm talking about to my dev branch.
Relevant code here: https://github.com/Caleydo/lineage/blob/da92c6232a825f552c444949bab99be332094d78/src/attributeData.ts#L77

### Expected behavior
The columns in the return from .objects() should match the columns in the return from .cols().

**Comment by alexsb** [comment]
In the latest commit this is demonstrated more explicitly: 
https://github.com/Caleydo/lineage/blob/anniesbrokendevbranch/src/attributeData.ts#L100

Output:

```
Printing names of active columns. This is CORRECT:
attributeData.ts:95 ["sex", "deceased", "suicide", "bdate", "ddate", "affection", "children", "x", "y", "generation", "hide", "type"]
attributeData.ts:100 These are the keys that are in the object. This is WRONG: 
attributeData.ts:101 ["suicide", "UPDBid", "pa", "RelativeID", "PaID", "sex", "OMEID", "x", "spouse", "type", "id", "affection"]
```

Clearly, the entries in the first should be the same as in the second, but they are not.

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_server/commit/3909e6b900aa8ac78f04383797c0a47a77ef51c1
