### ISSUE TITLE
Row slicing for table views is broken

### ISSUE THREAD

**Issue by alexsb** [phovea/phovea_core#92]
Row slicing of tables using view produces wrong results. 

The assumption is that a join() of a range takes first the col range, then the row range. 

This is demonstrated in the phovea_demos project, around this line: 

https://github.com/Caleydo/phovea_demos/commit/f78dc9cf66a65d56d7206e03178317584bfba961#diff-6d0c82cc6c66c68f45e4f2263d535897R268

### Observed behavior
* The size of the Table is expected 12, 3 as in 12 columns and 3 rows. It is WRONG 12, 14 - no idea where the 14 came from
`UsingTable.ts:272 [12, 14]`
* The table has only three columns left

### Expected behavior
* A view that preserves all columns and slices the rows.

**Comment by sgratzl** [comment]
> The assumption is that a join() of a range takes first the col range, then the row range.

the order is like: row, col

the same order what you get when using the `desc.size`, `ITable.dim`

**Comment by alexsb** [comment]
Well, we tried that of course. This does not fix the problem though. See phovea_demo:

https://github.com/Caleydo/phovea_demos/commit/274ebbb2892cabd7a2dd0b55f62e328c0b4ba200

**Comment by sgratzl** [comment]
see also #94 

in the meanwhile: https://github.com/Caleydo/phovea_demos/commit/773a05c1b71c1628c6d2bb8434deadb79a199703 use the direct access to meta data that are correct

**Comment by alexsb** [comment]
The data isn't sliced either:

https://github.com/Caleydo/phovea_demos/commit/9c3ab03920559858d3e0ebddb0ff3d3047878f75#diff-6d0c82cc6c66c68f45e4f2263d535897R283 

![image](https://cloud.githubusercontent.com/assets/2039375/23665868/ef045050-0316-11e7-8f03-384a4c4d863b.png)

**Comment by alexsb** [comment]
Was an out-of-date branch relative to some bug fix.
